title: JongHoBlog # your site title
author: jonghopark95
email: jong951005@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  이것저것 끄적끄적
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonghopark95.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: # replace with your_twitter_username or comment to remove link from footer
github_username: jonghopark95 # replace with your_github_username or comment to remove link from footer
instagram_username: jonghopark95 # replace with your_instagram_username or comment to remove link from footer
social:
  name: 박종호
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

disqus:
  shortname: disqus_OWfoyghYRX # to enable comments replace with your_disqus_shortname

# THEME SETTINGS
navigation: # Navigation links
  - { name: "test", link: "/test" }
  - { name: "About", link: "/about" }
  - { name: "Contact", link: "/contact" }

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ["_pages"]
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
